### ISSUE TITLE
Do something useful with images

### ISSUE THREAD

**Issue by grifferz** [chrisjrob/sluggle#10]
```
<@grifferz> http://www.dinkum.net/assets/milkshakes-01.jpg
<sluggle> grifferz: http://tinyurl.com/hmo6sao - Title lookup failed - WoT is good (60).
<find> grifferz: http://a.vu/bu65 - JPG: 313x387 (11.6K)
```

**Comment by chrisjrob** [comment]
Probably makes sense just to skip title lookup on non-html files, unless you have a view on what might be useful on an image and on other non-html files?

**Comment by grifferz** [comment]
I would consider the type, dimensions and other metadata of the image as interesting, like find does above. :)

**Comment by chrisjrob** [comment]
I am used to perlmagick, so shouldn't be difficult; although not sure I want to be downloading large images in order to determine metadata that is only of marginal use. I think I have max_size set to 8MB at present, so I guess images over that size won't work, which is probably a reasonable compromise.
